# TYPE  DATABASE        USER            ADDRESS                 METHOD
#local   all             postgres                                peer
#host    all             all             all            md5
# do not let the "postgres" superuser login via a certificate
#hostssl all             postgres        ::/0                    reject
#hostssl all             postgres        0.0.0.0/0               reject
#
# Allow host connections (localhost:5435): Docker bridge IPs and localhost
host    all             all             172.20.0.0/16           md5
host    all             all             172.17.0.0/16           md5
host    all             all             127.0.0.0/8              md5
host    all             all             ::1/128                 md5