version: "3.8"
services:
    nginx:
        restart: always
        environment:
        - 'LETSENCRYPT_EMAIL=thancock@mhtc.co.uk'
        - 'LETSENCRYPT_HOST=qwc2.mhtc.co.uk'
        - 'VIRTUAL_HOST=qwc2.mhtc.co.uk'

networks:
  default:
    external: true
    name: qgis-net